const stats = [
  {
    figure: '~52 min',
    label: 'Average time to process one document packet',
  },
  {
    figure: '$0',
    label: 'Revenue generated by any of that manual work',
  },
  {
    figure: 'Again & again',
    label: 'The same false flags, on every new supplier',
  },
]

export function Problem() {
  return (
    <section className="border-y border-border bg-secondary/60">
      <div className="mx-auto max-w-6xl px-6 py-16 lg:py-20">
        <div className="max-w-2xl">
          <p className="text-sm font-medium text-bronze">The problem</p>
          <h2 className="mt-3 text-balance text-3xl font-medium tracking-tight text-foreground sm:text-4xl">
            Every supplier starts from scratch.
          </h2>
          <p className="mt-4 text-pretty text-lg leading-relaxed text-muted-foreground">
            Onboarding a new supplier means manually reading registration
            documents, bank letters, and insurance certificates, cross-checking
            them, and chasing exceptions. It&apos;s slow, repetitive, and every
            tool you&apos;ve tried processes the 500th document exactly as
            cluelessly as the first.
          </p>
        </div>

        <div className="mt-10 grid gap-4 sm:grid-cols-3">
          {stats.map((s) => (
            <div
              key={s.label}
              className="rounded-xl border border-border bg-card p-6"
            >
              <p className="text-2xl font-medium tracking-tight text-foreground">
                {s.figure}
              </p>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                {s.label}
              </p>
            </div>
          ))}
        </div>
        <p className="mt-6 text-sm text-tertiary">
          Figures are illustrative of typical industry numbers, not a guarantee.
        </p>
      </div>
    </section>
  )
}
